### ISSUE TITLE
[bootloader] toggle /boot ro/rw for write ops on systems where /boot is ro by default

### ISSUE THREAD

**Issue by bmr-cymru** [snapshotmanager/boom-boot#72]
Image Mode and bootc container deployments mount the `/boot` file system as read-only by default:

```
[root@localhost ~]# bootc status
apiVersion: org.containers.bootc/v1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: localhost/rhel10-test1:latest
    transport: registry
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: localhost/rhel10-test1:latest
        transport: registry
      version: 10.20250116.0
      timestamp: null
      imageDigest: sha256:41cd22309b7ff1200b1f26e3567717864de3d5d420036f008f4648c3b59b98a7
    cachedUpdate: null
    incompatible: false
    pinned: false
    store: ostreeContainer
    ostree:
      checksum: 9ae97b6d3796af0414a3fe026cf3ce2dc66f01990ea33259e8244ef03c788fe5
      deploySerial: 0
  rollback: null
  rollbackQueued: false
  type: bootcHost
```

```
[root@localhost ~]# findmnt -s
TARGET SOURCE                                    FSTYPE OPTIONS
/boot  UUID=5de3bcfe-e14b-415a-aa49-a7e50aec13d2 auto   ro
[root@localhost ~]# mount | grep boot
/dev/vda2 on /boot type xfs (ro,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,noquota)
```

The `boom` command should treat this situation like `bootupctl` and remount ro/rw around operations that need to write to `/boot`.
